# Use the official Nginx image as the base image
FROM nginx

# Copy the index.html file to the default Nginx HTML directory
COPY index.html /usr/share/nginx/html

# Expose port 80 to allow incoming traffic
EXPOSE 80